from pydantic import BaseModel

class Task(BaseModel):
    title:str
    description:str
    status:str

# his model is used when you create or update a task.

# ➡️ Why no id?
# Because when the user sends data to create a task, the user does not provide the task ID.
# The ID is generated by the database.
class TaskWithId(Task):
    id:int

# This model is used when the API returns data (GET requests, created tasks, updated tasks, etc.).

# ➡️ Why include id?
# Because when the database returns a task record, it always includes an ID.